export type DocumentVaultCategory =
  | 'werk'
  | 'wonen'
  | 'contracten'
  | 'overheid'
  | 'identiteit'
  | 'mijn_zaken';

export type DocumentStatus = 'uploading' | 'analyzing' | 'analyzed' | 'error' | 'klaar';

export type DocumentSource = 'upload' | 'photo' | 'scan' | 'generated';

export interface ExtractedField {
  key: string;
  label: string;
  value: string;
  editable: boolean;
  /** The reader was not certain about this value — the user should check it. */
  needsConfirmation?: boolean;
}

export interface LegalDocument {
  id: string;
  name: string;
  category: DocumentVaultCategory;
  source: DocumentSource;
  status: DocumentStatus;
  mimeType: string;
  fileSizeLabel: string;
  uploadedAt: string;
  caseId?: string;
  documentTitle?: string;
  extractedFields?: ExtractedField[];
  thumbnailColor?: string;
}

export type RiskLevel = 'hoog' | 'gemiddeld' | 'laag';

export type ContractTemplateId =
  | 'arbeidsovereenkomst'
  | 'freelanceovereenkomst'
  | 'nda'
  | 'leningsovereenkomst'
  | 'samenwerkingsovereenkomst';

export interface ContractTemplate {
  id: ContractTemplateId;
  title: string;
  description: string;
}

export interface GeneratedLegalDocument {
  id: string;
  caseId: string;
  title: string;
  recipient: string;
  subject: string;
  reference?: string;
  paragraphs: string[];
  usedFacts: string[];
  attachments: string[];
  status: 'concept' | 'goedgekeurd' | 'verzonden';
  createdAt: string;
  /** Id of the pending Action in the backend, when this document was
   * generated by the real agent — needed to call the real approve endpoint. */
  backendActionId?: string;
}
